language: php
php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.1"
matrix:
  allow_failures:
    - php: nightly
services: postgresql
before_script:
  - psql -c 'CREATE DATABASE pomm_test' -U postgres -h 127.0.0.1 postgres
  - psql -c 'CREATE EXTENSION hstore' -U postgres -h 127.0.0.1 pomm_test
  - psql -c 'CREATE EXTENSION ltree' -U postgres -h 127.0.0.1 pomm_test
install:
  - composer install --dev
  - composer update atoum/atoum --prefer-stable
script: php vendor/atoum/atoum/bin/atoum -d sources/tests/Unit/

