language: php
php:
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"
  - "7.3"
  - "nightly"
matrix:
  allow_failures:
    - php: "nightly"
services: postgresql
before_script:
  - psql -c 'CREATE DATABASE pomm_test' -U postgres -h 127.0.0.1 postgres
  - psql -c 'CREATE EXTENSION hstore' -U postgres -h 127.0.0.1 pomm_test
  - psql -c 'CREATE EXTENSION ltree' -U postgres -h 127.0.0.1 pomm_test
install:
  - composer update --dev
  - composer update atoum/atoum --prefer-stable
script:
  - php vendor/bin/phpcs --standard=psr2 --runtime-set ignore_warnings_on_exit true --report=summary sources
  - php vendor/bin/atoum --no-code-coverage -d sources/tests/Unit

